---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: avail-kate-node
  namespace: blockchain
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: avail-kate-node
          args:
            - --rpc-external
            - --rpc-port=9933
            - --rpc-cors=all
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
