---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avail-node
  namespace: blockchain
  labels:
    app.kubernetes.io/instance: avail-node
    app.kubernetes.io/name: avail-node
    app.kubernetes.io/version: 1.7.2
