---
apiVersion: v1
kind: Service
metadata:
  name: avail-node
  labels:
    app.kubernetes.io/instance: avail-node
    app.kubernetes.io/name: avail-node
    app.kubernetes.io/version: 1.7.2
spec:
  type: ClusterIP
  ports:
    - port: 9933
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 30333
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    app.kubernetes.io/instance: avail-node
    app.kubernetes.io/name: avail-node
